### ISSUE TITLE
Missing examples of code_scanning_alert payloads with "sender"

### ISSUE THREAD

**Issue by G-Rath** [octokit/webhooks#229]
According to the [docs](https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads#code_scanning_alert), when the action is `reopened_by_user` or `closed_by_user`, the payload for `code_scanning_alert` will have a `sender` property.

Since there are no examples of these actions, the types generated in `webhooks.js` doesn't have `sender` at all.

I'm not familiar enough with code scanning to generate these events to capture their payloads, but if I do capture one I'll PR it :)

**Comment by gr2m** [comment]
I asked for help from GitHub

**Comment by G-Rath** [comment]
@gr2m cheers! Are you happy for me to open new issues for any others I find like this?

**Comment by gr2m** [comment]
absolutely, please do! Ideally we can add payload examples for all of them, which will help us with creating a complete schema via https://github.com/octokit/webhooks/pull/186

**Comment by marcogario** [comment]
:wave: The `sender` field is not specific to code scanning, but it appears in all webhooks. https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads#webhook-payload-object-common-properties

Nevertheless, here is an example of a full response for the `closed_by_user` event. Note that the `dismissed_by` identifier the actor that dismissed the alert:

<details><summary>Response</summary>
<pre>
{
  "action": "closed_by_user",
  "alert": {
    "number": 5,
    "created_at": "2020-10-08T18:32:17Z",
    "url": "https://api.github.com/repos/Codertocat/Hello-World/code-scanning/alerts/5",
    "html_url": "https://github.com/Codertocat/Hello-World/security/code-scanning/5",
    "instances": [
      {
        "ref": "refs/heads/master",
        "analysis_key": ".github/workflows/codeql-analysis.yml:analyze",
        "environment": "{\"language\":\"javascript\"}",
        "state": "dismissed"
      },
      {
        "ref": "refs/pull/11/head",
        "analysis_key": ".github/workflows/codeql-analysis.yml:analyze",
        "environment": "{\"language\":\"javascript\"}",
        "state": "dismissed"
      }
    ],
    "state": "dismissed",
    "dismissed_by": {
      "login": "mona",
      "id": 1058447,
      "node_id": "MDQ6VXNlcjEwNTg0NDc=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/1058440?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mona",
      "html_url": "https://github.com/mona",
      "followers_url": "https://api.github.com/users/mona/followers",
      "following_url": "https://api.github.com/users/mona/following{/other_user}",
      "gists_url": "https://api.github.com/users/mona/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mona/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mona/subscriptions",
      "organizations_url": "https://api.github.com/users/mona/orgs",
      "repos_url": "https://api.github.com/users/mona/repos",
      "events_url": "https://api.github.com/users/mona/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mona/received_events",
      "type": "User",
      "site_admin": true
    },
    "dismissed_at": "2020-12-14T12:55:41Z",
    "dismissed_reason": "false positive",
    "rule": {
      "id": "js/xss",
      "severity": "error",
      "description": "Client-side cross-site scripting"
    },
    "tool": {
      "name": "CodeQL",
      "version": null
    }
  },
  "ref": "",
  "commit_oid": "",
  "repository": {
    "id": 297438169,
    "node_id": "MDEwOlJlcG9zaXRvcnkyOTc0MzgxNjk=",
    "name": "Hello-World",
    "full_name": "Codertocat/Hello-World",
    "private": true,
    "owner": {
      "login": "Codertocat",
      "id": 30846345,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjMwODQ2MzQ1",
      "avatar_url": "https://avatars0.githubusercontent.com/u/30846345?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Codertocat",
      "html_url": "https://github.com/Codertocat",
      "followers_url": "https://api.github.com/users/Codertocat/followers",
      "following_url": "https://api.github.com/users/Codertocat/following{/other_user}",
      "gists_url": "https://api.github.com/users/Codertocat/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Codertocat/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Codertocat/subscriptions",
      "organizations_url": "https://api.github.com/users/Codertocat/orgs",
      "repos_url": "https://api.github.com/users/Codertocat/repos",
      "events_url": "https://api.github.com/users/Codertocat/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Codertocat/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "html_url": "https://github.com/Codertocat/Hello-World",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/Codertocat/Hello-World",
    "forks_url": "https://api.github.com/repos/Codertocat/Hello-World/forks",
    "keys_url": "https://api.github.com/repos/Codertocat/Hello-World/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Codertocat/Hello-World/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Codertocat/Hello-World/teams",
    "hooks_url": "https://api.github.com/repos/Codertocat/Hello-World/hooks",
    "issue_events_url": "https://api.github.com/repos/Codertocat/Hello-World/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Codertocat/Hello-World/events",
    "assignees_url": "https://api.github.com/repos/Codertocat/Hello-World/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Codertocat/Hello-World/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Codertocat/Hello-World/tags",
    "blobs_url": "https://api.github.com/repos/Codertocat/Hello-World/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Codertocat/Hello-World/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Codertocat/Hello-World/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Codertocat/Hello-World/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Codertocat/Hello-World/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Codertocat/Hello-World/languages",
    "stargazers_url": "https://api.github.com/repos/Codertocat/Hello-World/stargazers",
    "contributors_url": "https://api.github.com/repos/Codertocat/Hello-World/contributors",
    "subscribers_url": "https://api.github.com/repos/Codertocat/Hello-World/subscribers",
    "subscription_url": "https://api.github.com/repos/Codertocat/Hello-World/subscription",
    "commits_url": "https://api.github.com/repos/Codertocat/Hello-World/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Codertocat/Hello-World/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Codertocat/Hello-World/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Codertocat/Hello-World/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Codertocat/Hello-World/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Codertocat/Hello-World/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Codertocat/Hello-World/merges",
    "archive_url": "https://api.github.com/repos/Codertocat/Hello-World/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Codertocat/Hello-World/downloads",
    "issues_url": "https://api.github.com/repos/Codertocat/Hello-World/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Codertocat/Hello-World/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Codertocat/Hello-World/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Codertocat/Hello-World/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Codertocat/Hello-World/labels{/name}",
    "releases_url": "https://api.github.com/repos/Codertocat/Hello-World/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Codertocat/Hello-World/deployments",
    "created_at": "2020-09-21T19:17:07Z",
    "updated_at": "2020-12-09T21:12:40Z",
    "pushed_at": "2020-12-09T21:12:38Z",
    "git_url": "git://github.com/Codertocat/Hello-World.git",
    "ssh_url": "git@github.com:Codertocat/Hello-World.git",
    "clone_url": "https://github.com/Codertocat/Hello-World.git",
    "svn_url": "https://github.com/Codertocat/Hello-World",
    "homepage": null,
    "size": 39,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 5,
    "license": null,
    "forks": 0,
    "open_issues": 5,
    "watchers": 0,
    "default_branch": "master"
  },
  "organization": {
    "login": "Codertocat",
    "id": 30846345,
    "node_id": "MDEyOk9yZ2FuaXphdGlvbjMwODQ2MzQ1",
    "url": "https://api.github.com/orgs/Codertocat",
    "repos_url": "https://api.github.com/orgs/Codertocat/repos",
    "events_url": "https://api.github.com/orgs/Codertocat/events",
    "hooks_url": "https://api.github.com/orgs/Codertocat/hooks",
    "issues_url": "https://api.github.com/orgs/Codertocat/issues",
    "members_url": "https://api.github.com/orgs/Codertocat/members{/member}",
    "public_members_url": "https://api.github.com/orgs/Codertocat/public_members{/member}",
    "avatar_url": "https://avatars0.githubusercontent.com/u/30846345?v=4",
    "description": "Demos and testing of GitHub security products"
  },
  "sender": {
    "login": "mona",
    "id": 1058447,
    "node_id": "MDQ6VXNlcjEwNTg0NDc=",
    "avatar_url": "https://avatars0.githubusercontent.com/u/1058447?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/mona",
    "html_url": "https://github.com/mona",
    "followers_url": "https://api.github.com/users/mona/followers",
    "following_url": "https://api.github.com/users/mona/following{/other_user}",
    "gists_url": "https://api.github.com/users/mona/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/mona/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/mona/subscriptions",
    "organizations_url": "https://api.github.com/users/mona/orgs",
    "repos_url": "https://api.github.com/users/mona/repos",
    "events_url": "https://api.github.com/users/mona/events{/privacy}",
    "received_events_url": "https://api.github.com/users/mona/received_events",
    "type": "User",
    "site_admin": true
  }
}


</pre>
</details> 

For the reopened_by_user event the payload is identical with the exception of the following fields.
```json
{
  "action": "reopened_by_user",
  "alert": {
    "state": "open",
    "dismissed_by": null,
    "dismissed_at": null,
    "dismissed_reason": null,
    ...
```

Hope this helps!

**Comment by G-Rath** [comment]
> The sender field is not specific to code scanning, but it appears in all webhooks.

In that case, the examples for `reopened` are incomplete as they're missing the `sender` field.

**Comment by bogdanap** [comment]
Hopefully, this should be fixed by https://github.com/octokit/webhooks/pull/366

**Comment by gr2m** [comment]
@G-Rath I assume this is resolved via #366?

**Comment by wolfy1339** [comment]
There still isn't an example for the `reopened_by_user` action. However with the schemas this isn't as much of an issue
